USE MASTER

DROP DATABASE MERCADO
CREATE DATABASE MERCADO

USE MERCADO

CREATE TABLE ENDERECOS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	LOGRADOURO VARCHAR(255) NOT NULL,
	NUMERO INT NULL,
	COMPLEMENTO VARCHAR(100) NULL,
	CEP CHAR(8) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	PAIS CHAR(2) NOT NULL DEFAULT 'BR',
	DT_CRIACAO DATETIME NOT NULL,
	DT_ATUALIZACAO TIMESTAMP NOT NULL,
	ATIVO BIT DEFAULT 1,
	CONSTRAINT PK_ENDERECOS PRIMARY KEY(ID),
)

CREATE TABLE CLIENTES (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(20) NOT NULL,
	SOBRENOME VARCHAR(50) NULL,
	CPF CHAR(11) NOT NULL,
	DATA_NASC DATE NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR (14) NOT NULL,
	SENHA VARBINARY NOT  NULL,
	ID_ENDERECO BIGINT NOT NULL,
	DT_CRIACAO DATETIME NOT NULL,
	DT_ATUALIZACAO TIMESTAMP NOT NULL,
	ATIVO BIT DEFAULT 1,
	CONSTRAINT PK_CLIENTES PRIMARY KEY(ID),
	CONSTRAINT UN_CLIENTES_CPF UNIQUE(CPF),
	CONSTRAINT FK_CLIENTES_ENDERECOS FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECOS(ID)
)

CREATE TABLE USUARIOS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(20) NOT NULL,
	SOBRENOME VARCHAR(50) NULL,
	CPF CHAR(11) NOT NULL,
	DATA_NASC DATE NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR (14) NOT NULL,
	SENHA VARBINARY NOT NULL,
	TIPO VARCHAR(10) NOT NULL,
	NIVEL TINYINT NOT NULL,
	ID_ENDERECO BIGINT NOT NULL,
	DT_CRIACAO DATETIME NOT NULL,
	DT_ATUALIZACAO TIMESTAMP NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_USUARIOS PRIMARY KEY(ID),
	CONSTRAINT UN_USUARIOS_CPF UNIQUE(CPF),
	CONSTRAINT CK_USUARIOS_NIVEL CHECK (NIVEL BETWEEN 1 AND 5),
	CONSTRAINT FK_USUARIOS_ENDERECOS FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECOS(ID)
)

CREATE TABLE PRODUTOS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	COD_BARRAS INT NOT NULL,
	COD_INTERNO INT NOT NULL,
	CATEGORIA VARCHAR(20) NOT NULL,
	NOME VARCHAR (100) NOT NULL,
	PRECO DECIMAL(20,2) NOT NULL,
	CLASSIFICACAO DECIMAL(2,1) NULL,
	DESCRICAO VARCHAR (200) NULL,
	QTD_ESTOQUE DECIMAL(10,3) NOT NULL,
	CRIADO_POR BIGINT NOT NULL,
	DT_CRIACAO DATETIME NOT NULL,
	ATUALIZADO_POR BIGINT NOT NULL,
	DT_ATUALIZACAO TIMESTAMP NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID),
	CONSTRAINT UN_PRODUTOS_COD_BARRAS UNIQUE(COD_BARRAS),
	CONSTRAINT UN_PRODUTOS_COD_INTERNO UNIQUE(COD_INTERNO),
	CONSTRAINT FK_PRODUTOS_CRIADO_POR_USUARIOS FOREIGN KEY(CRIADO_POR) REFERENCES USUARIOS(ID),
	CONSTRAINT FK_PRODUTOS_ATUALIZADO_POR_USUARIOS FOREIGN KEY(ATUALIZADO_POR) REFERENCES USUARIOS(ID)
	
)

CREATE TABLE CUPONS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	CODIGO VARCHAR(20) NOT NULL,
	DESCRICAO VARCHAR(200) NULL,
	DESCONTO DECIMAL(5,2) NOT NULL,
	QTD INT NOT NULL,
	CRIADO_POR BIGINT NOT NULL,
	DT_CRIACAO DATETIME NOT NULL,
	ATUALIZADO_POR BIGINT NOT NULL,
	DT_ATUALIZACAO TIMESTAMP NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_CUPONS PRIMARY KEY(ID),
	CONSTRAINT UN_CUPONS_CODIGO UNIQUE(CODIGO),
	CONSTRAINT CK_CUPONS_DESCONTO CHECK (DESCONTO BETWEEN 0 AND 100),
	CONSTRAINT FK_CUPONS_CRIADO_POR_USUARIOS FOREIGN KEY(CRIADO_POR) REFERENCES USUARIOS(ID),
	CONSTRAINT FK_CUPONS_ATUALIZADO_POR_USUARIOS FOREIGN KEY(ATUALIZADO_POR) REFERENCES USUARIOS(ID)
)

CREATE TABLE PAGAMENTOS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	METODO VARCHAR(20) NOT NULL,
	DESCRICAO VARCHAR(200) NULL,
	CRIADO_POR BIGINT NOT NULL,
	DT_CRIACAO DATETIME NOT NULL,
	ATUALIZADO_POR BIGINT NOT NULL,
	DT_ATUALIZACAO TIMESTAMP NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_PAGAMENTOS PRIMARY KEY(ID),
	CONSTRAINT FK_PAGAMENTOS_CRIADO_POR_USUARIOS FOREIGN KEY(CRIADO_POR) REFERENCES USUARIOS(ID),
	CONSTRAINT FK_PAGAMENTOS_ATUALIZADO_POR_USUARIOS FOREIGN KEY(ATUALIZADO_POR) REFERENCES USUARIOS(ID)
)

CREATE TABLE COMPRAS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_CLIENTE BIGINT NOT NULL,
	ID_USUARIO BIGINT NULL,
	ID_CUPOM BIGINT NULL,
	ID_ENDERECO BIGINT NULL,
	ID_PAGAMENTO BIGINT NOT NULL,
	QTD_PRODUTOS INT NOT NULL,
	QTD_ITENS DECIMAL(20,3) NOT NULL,
	SUBTOTAL DECIMAL(20,2) NOT NULL,
	DESCONTO_VALOR DECIMAL(20,2) NOT NULL,
	DESCONTO_PERCENTUAL DECIMAL(5,2) NOT NULL,
	TOTAL DECIMAL(20,2) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	PLATAFORMA CHAR(3) NOT NULL,
	DT_CRIACAO DATETIME NOT NULL,
	DT_ATUALIZACAO TIMESTAMP NOT NULL,
	CONSTRAINT PK_COMPRAS PRIMARY KEY(ID),
	CONSTRAINT FK_COMPRAS_CLIENTES FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID),
	CONSTRAINT FK_COMPRAS_USUARIOS FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID),
	CONSTRAINT FK_COMPRAS_CUPONS FOREIGN KEY(ID_CUPOM) REFERENCES CUPONS(ID),
	CONSTRAINT FK_COMPRAS_ENDERECOS FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECOS(ID),
	CONSTRAINT FK_COMPRAS_PAGAMENTOS FOREIGN KEY(ID_PAGAMENTO) REFERENCES PAGAMENTOS(ID),
	CONSTRAINT CK_COMPRAS_PLATAFORMA CHECK(PLATAFORMA IN('ECM', 'PDV'))
)

CREATE TABLE ITENS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ID_COMPRA BIGINT NOT NULL,
	ID_CUPOM BIGINT NOT NULL,
	ID_PRODUTO BIGINT NOT NULL,
	QTD DECIMAL(20,3) NOT NULL,
	SUBTOTAL DECIMAL(20,2) NOT NULL,
	DESCONTO_VALOR DECIMAL(20,2) NOT NULL,
	DESCONTO_PERCENTUAL DECIMAL(5,2) NOT NULL,
	TOTAL DECIMAL(20,2) NOT NULL,
	DT_CRIACAO DATETIME NOT NULL,
	DT_ATUALIZACAO TIMESTAMP NOT NULL,
	CONSTRAINT PK_ITENS PRIMARY KEY(ID),
	CONSTRAINT FK_ITENS_COMPRAS FOREIGN KEY(ID_COMPRA) REFERENCES COMPRAS(ID),
	CONSTRAINT FK_ITENS_CUPONS FOREIGN KEY(ID_CUPOM) REFERENCES CUPONS(ID),
	CONSTRAINT FK_ITENS_PRODUTOS FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID)
)

